
/*-
 * Copyright (c) 2009 UCHIYAMA Yasushi.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* These data are overwrited by jmp instruction on execution time */
#include <asm/machine.h>
	H8ARCH
	.section .vector_link_table
	.globl _jmp07
_jmp07: .long	0
	.globl _jmp08
_jmp08: .long	0
	.globl _jmp09
_jmp09: .long	0
	.globl _jmp10
_jmp10: .long	0
	.globl _jmp11
_jmp11: .long	0
	.globl _jmp12
_jmp12: .long	0
	.globl _jmp13
_jmp13: .long	0
	.globl _jmp14
_jmp14: .long	0
	.globl _jmp15
_jmp15: .long	0
	.globl _jmp16
_jmp16: .long	0
	.globl _jmp17
_jmp17: .long	0
	.globl _jmp18
_jmp18: .long	0
	.globl _jmp19
_jmp19: .long	0
	.globl _jmp20
_jmp20: .long	0
	.globl _jmp21
_jmp21: .long	0
	.globl _jmp22
_jmp22: .long	0
	.globl _jmp23
_jmp23: .long	0
	.globl _jmp24
_jmp24: .long	0
	.globl _jmp25
_jmp25: .long	0
	.globl _jmp26
_jmp26: .long	0
	.globl _jmp27
_jmp27: .long	0
	.globl _jmp28
_jmp28: .long	0
	.globl _jmp29
_jmp29: .long	0
	.globl _jmp30
_jmp30: .long	0
	.globl _jmp31
_jmp31: .long	0
	.globl _jmp32
_jmp32: .long	0
	.globl _jmp33
_jmp33: .long	0
	.globl _jmp34
_jmp34: .long	0
	.globl _jmp35
_jmp35: .long	0
	.globl _jmp36
_jmp36: .long	0
	.globl _jmp37
_jmp37: .long	0
	.globl _jmp38
_jmp38: .long	0
	.globl _jmp39
_jmp39: .long	0
	.globl _jmp40
_jmp40: .long	0
	.globl _jmp41
_jmp41: .long	0
	.globl _jmp42
_jmp42: .long	0
	.globl _jmp43
_jmp43: .long	0
	.globl _jmp44
_jmp44: .long	0
	.globl _jmp45
_jmp45: .long	0
	.globl _jmp46
_jmp46: .long	0
	.globl _jmp47
_jmp47: .long	0
	.globl _jmp48
_jmp48: .long	0
	.globl _jmp49
_jmp49: .long	0
	.globl _jmp50
_jmp50: .long	0
	.globl _jmp51
_jmp51: .long	0
	.globl _jmp52
_jmp52: .long	0
	.globl _jmp53
_jmp53: .long	0
	.globl _jmp54
_jmp54: .long	0
	.globl _jmp55
_jmp55: .long	0
	.globl _jmp56
_jmp56: .long	0
	.globl _jmp57
_jmp57: .long	0
	.globl _jmp58
_jmp58: .long	0
	.globl _jmp59
_jmp59: .long	0
	.globl _jmp60
_jmp60: .long	0
